### ISSUE TITLE
Can't see matched text in a list/intellisense

### ISSUE THREAD

**Issue by stkb** [Elijah-Barker/high-contrast-light#1]
Thanks very much for this theme; it's my favorite light theme!

I've just had a small problem with it that this image demonstrates:

<img width="236" alt="ThemeColors" src="https://user-images.githubusercontent.com/6125444/124346711-94c49300-dbe0-11eb-9711-37b08e425d35.png">

Here the matched word "preferences" can't be seen in the focused item, because the text color (1) is almost the same blue color as the focused item background (2). It's more annoying when using intellisense.

It needs a change to the colors of either (1) or (2). An option is just to make (1) the same (white) color as (3), since the matched text is also made bold, which makes it easy to distinguish anyway.

From some investigating I've found the colors used:
1. `list.focusHighlightForeground`
2. `quickListInput.focusBackground`
3. `quickListInput.focusForeground`
4. `list.highlightForeground`

I've I can fix it for myself for now by using the "workbench.colorCustomizations" setting in my settings.json.

**Comment by Elijah-Barker** [comment]
I'm glad you enjoy the theme!  Fixed in db898a1c8092fecba135aadf0e268eb585b5576e

**Comment by stkb** [comment]
Looks great, thanks! 👍
